### ISSUE TITLE
Filesystem & Decoding

### ISSUE THREAD

**Issue by hexlgaming** [sniklaus/youtube-watchmarker#10]
I've got a question. Question being that I got a really long watch list & I wanted to back it up, I don't know what filesystem to choose though. I'd like to look at the links seperately, even in a text file if neccesary. If I try to open the backup file with a notepad, I always just get random strings of letters & numbers. Is there a posibilety to enable me to backup my watchhistory in for of links that I can use universially & not just in the plugin? I want to be on the safe side if anything'd ever happen to the tools I use. I hope you can understand what I mean..

**Comment by sniklaus** [comment]
The save [1] and load [2] mechanism utilizes as Base64 encoding, which is why you do not see the links right away. You should be able to decode and read it using a Base64 decoder.

[1] https://github.com/sniklaus/youtube-watchmarker/blob/master/background.js#L124
[2] https://github.com/sniklaus/youtube-watchmarker/blob/master/content/index.js#L141

**Comment by sniklaus** [comment]
The following Python script should allow you to open and iterate over the videos in an exported database, I hope that this will be sufficient for most people trying to read an exported database.

```
import base64
import json

for objVideo in json.loads(base64.b64decode(open('CHANGETHIS.database', 'r').read())):
    print(objVideo)
# end
```
