### ISSUE TITLE
Clarify behaviour of Youtube synchronization

### ISSUE THREAD

**Issue by JayFoxRox** [sniklaus/youtube-watchmarker#11]
I've disabled the YouTube internal logging, in an effort to minimize privacy invasion (probably not very effective with Google, but whatever). There's also no reason why I should depend on a watchlist stored on their servers, when I can keep track locally myself.

Therefore I want to use this plugin as an offline solution and it seems to work. However, this sounds like it defeats the purpose:

> In order to synchronize your timeline across multiple devices, **this addon fetches your browsing information directly from your Youtube [sic] account. It will in this regard automatically fetch the most recent activity every hour**, but you can manually initiate a complete fetch of the entire browsing information. 

- What exactly does happen?
- Does it contact Google/YouTube actively?
- When exactly does this happen and can I prevent it somehow?
- Does it also happen when I'm not on YouTube?
- Does it only happen when being on YouTube the next time after the last visit was more than an hour ago?
- Why does this have to happen?
- Depending on how it's implemented, could it simply be disabled by choosing a date far ahead in the future (01.01.9999; and probably entering it in some config file)?

I only have one device anyway, and even if I didn't, I'd rather synchronize my watchlist differently or not at all.
I've tried to find the responsible code for this feature, but could not see it when skimming over the codebase (also I'm not a JS coder).

**Comment by sniklaus** [comment]
The code in question can be found in the background.js file.

https://github.com/sniklaus/youtube-watchmarker/blob/4d3daaf11638ade7b4846a2e0cc0049886c302be/background.js#L543

It is triggered by an hourly alarm further below in the same file.

https://github.com/sniklaus/youtube-watchmarker/blob/4d3daaf11638ade7b4846a2e0cc0049886c302be/background.js#L1220

You can disabling it by commenting out the relevant code in the alarm callback.

**Comment by metal450** [comment]
I'm also a bit confused by what this does, & would love clarification. From your comment I understand how to disable it, but don't really understand from the description what it's actually doing. "this addon fetches your browsing information directly from your Youtube account" - makes it sound like it's i.e. visiting YouTube & trying to scrape (download) my watch history...but if so, I don't see how that implements syncing between devices? If not...what is it doing? I sit *sending* info to YouTube?

Thanks for the clarification :)

**Comment by metal450** [comment]
Hi sniklaus,

Since it looks like you're back online answering some other issues...any feedback on this? Please?

**Comment by sniklaus** [comment]
The extension essentially visits https://www.youtube.com/feed/history and imports these videos into its list of watched videos. You can disable this feature in the "Condition" setting.

If you have multiple devices that are signed into the same account then they will all sync with this history automatically, making sure that they are all up to date. This extension does not send any information to Youtube. Having multiple devices without having them logged into the same account on Youtube will prevent them from gathering the same information about which videos have been watched.

**Comment by metal450** [comment]
Ah, understood. So if one's goal was to use this as a *replacement* for YouTube's built-in watch history (i.e. so I could view YouTube anonymously without letting Google track my history, but still have this as a "local" watch history), it wouldn't work to sync that history between PCs.

Related question, then: might it be possible to set up a 3rd party file syncing software, like i.e. syncthing, to point to wherever in the Firefox profile this stores its history list?  Obviously it wouldn't work to merge changes if they occurred at both ends simultaneously, but as long as it syncs from one to the other before the other launches Firefox, that should bring the recent changes over to the out-of-date PC?

Do you know exactly where in the Firefox profile folder this history is stored? Perhaps would it be possible to customize the location, so that such "external" syncing between PCs could be performed?

**Comment by sniklaus** [comment]
Yep, that would require a sever to synchronize between devices. But I would much rather 1) not have to maintain such a server, 2) not implement the end-to-end encryption that would be necessary to maintain privacy, and 3) explain the end-to-end encryption to users that raise privacy concerns.

I would be surprised if syncing the database file would work without any hiccups due to concurrent writes. I just tried to find the file in which Firefox stores the IndexedDB instance of the extension but was unable to locate it, you could go to about:profiles and open your profile directory to give it a try yourself.

The easiest solution may be to sync your browser history across devices, which will ensure that the Youtube Watchmarker will extract the same information across all your devices. This may, of course, be a privacy concern for you, but maybe they use end-to-end encryption already.

**Comment by metal450** [comment]
>>The easiest solution may be to sync your browser history across devices, which will ensure that the Youtube Watchmarker will extract the same information across all your devices.

Oh, duh - why didn't I think of that!  Hehe.  Well in that case, what about simply having the option for it to automatically do the "browser history import" every so often, i.e. on launch? That seems like it would automatically handle keeping the multiple histories up-to-date?

**Comment by sniklaus** [comment]
It already syncs with the browser history of the last week every hour. :+1: 

https://github.com/sniklaus/youtube-watchmarker/blob/1c79ffda2d1960eb20daa17c3694972bb99dbae3/background.js#L1389-L1415

**Comment by metal450** [comment]
Well then...nice!  Haha easy solution :D

**Comment by JayFoxRox** [comment]
> This extension does not send any information to Youtube.

My issue witth that statement is that it *does* ping google when requesting the history. Therefore I'd like to disable this fetching of the history as part of this plugin (in the FireFox Add-On preferences).

> The extension essentially visits https://www.youtube.com/feed/history and imports these videos into its list of watched videos. You can disable this feature in the "Condition" setting.

I'm using FireFox and my Add-On preferences don't seem to have that option?

I'd like to be individually be able to tell it how far into the history it should synchronize and wether it should do this at all for each source (YouTube history + local browsing history). If a YouTube history is disabled it should not even ping it. Basically https://github.com/sniklaus/youtube-watchmarker/issues/11#issuecomment-397843646 but as a option in the preferences.

**Comment by sniklaus** [comment]
The setting got included in the most recent release. So you either do not have the most recently released version or you are looking at the wrong preferences. The settings I am referring to is the page that opens up once you click on the icon of the Youtube Watchmarker.

![Screenshot_2020-04-02_20-27-23](https://user-images.githubusercontent.com/1238034/78321399-af611580-7520-11ea-891f-7493cfa6ac3a.png)

**Comment by JayFoxRox** [comment]
> The setting got included in the most recent release.

Cool! It would be nice if you could start using proper git commit messages to make it easier to follow development.

> The settings I am referring to is the page that opens up once you click on the icon of the Youtube Watchmarker.

Cheers! I had forgotten about those preferences. I don't keep the icon on my menu bars normally.

I'd suggest to make the messages more explicit along the lines of "Allow access to my browsing history" and "Allow access to YouTube.com watch history".
