### ISSUE TITLE
Clicking on timestamps refreshes webpage?

### ISSUE THREAD

**Issue by AndyL964** [sniklaus/youtube-watchmarker#19]
Hi there,

I've recently noticed a minor issue with this add-on.
Clicking on timestamps (such as a video's description) causes the entire page to reload rather than just skipping ahead to that particular part of the video.

I don't really understand why an add-on that simply marks videos as watched would cause something like this to happen, which although isn't very annoying, it makes me have to wait around 3 to 4 seconds for the page to load before the video starts to play again.

**Comment by TheHaricover** [comment]
Hi !

I got this issue too ! For now, I'll just deactivate the extension.
Otherwise, nothing to say, it's great work !

I'm on Firefox Quantum 69.0.3 (64 bits)

If you want more info, feel free to ask.

**Comment by sniklaus** [comment]
I am happy to say that I just released a new version where this problem should no longer exist. Thank you again for bringing this to my attention, please let me know in case the issue still prevails.

**Comment by sojinsamuel** [comment]
i am building a chrome extension, let just say my chrome extension generated a time stamp like and displayed it by manipulating a part of the page in the youtube website.
`<li><a href="https://www.youtube.com/watch?v=VdCcQ3m3yoo&t=0s"><strong>0:00</strong> - Introduction to the topic and the purpose of the video.</a></li>
`
but when i click on it, it refreshes the page, instead of just leading the time line to that particluar point (with out refreshing)

i tried this version to:
` href="watch?v=VdCcQ3m3yoo&t=0s"`

still the page reloads. 

is there a solution that i can use to solve this issue to stop the reloading but still make it work.
