### ISSUE TITLE
Support for "invidio.us"

### ISSUE THREAD

**Issue by Agych** [sniklaus/youtube-watchmarker#28]
There is an alternative Youtube front-end site www.invidio.us that many people use for privacy concerns in order to not be tracked by Google, and not deal with other Youtube annoyances.
Would that be possible to add the support for the invidio.us site in the extension?
So that videos watched on invidio.us as well as on youtube.com are remembered in the database.
And the "Watched" dimmed overlay is shown on invidio.us and youtube.com for all videos watched on both of these sites.
The video links look very similar to the youtube ones, just the "youtube.com" replaced with "invidio.us"

**Comment by DonaldTsang** [comment]
The main site is dead, so please apply this to the other instances.
Note: in order to do that you need a place to store already watched videos since Invidious does not store any data.

**Comment by sniklaus** [comment]
I am under the impression that there are multiple domains that host invidious: https://redirect.invidious.io/

Since these domains change over time and since there is no officially invidious instance as per [1], it would require perpetual updates to the Youtube Watchmarker. I am afraid that I do not have the time/energy to support these recurrent updates, my apologies.

[1] https://github.com/iv-org/invidious/issues/1694

**Comment by Agych** [comment]
@sniklaus,

Could be just a text field in the settings where the user by himself could paste the domain(s) of the favourite/used instances, 1 or many instances each one on its string.
`
invidious.snopyta.org
ytprivate.com
notyoutube.org
yewtu.be
`
Let the user himself control this list = no need to maintain the list of instances by the dev.

**Comment by sniklaus** [comment]
Good suggestion on paper. However, you have to modify the manifest for doing so.

https://github.com/sniklaus/youtube-watchmarker/blob/740c361662f606ac3b75bfbc5ce4269b952f39c9/manifest.json#L10

Essentially, you need to tell users ahead of time which websites you would like to interact with (for security reasons). Adding more websites to this list after the fact the extension has been installed is not possible (at least as far as I know since it would be bad for security if you could).

**Comment by Agych** [comment]
Could giving the extension permissions to work on all sites be the solution?

**Comment by sniklaus** [comment]
Potentially yes, but then you are subject to more scrutiny in the code reviewing process as well as reviews from users who would rather the extension not be able to read data from all the sites they visit. You are welcome to fork the project though and add this feature yourself. :slightly_smiling_face:

**Comment by Unicorn-42** [comment]
Looking forward to Invidious and Piped support too!
