### ISSUE TITLE
Unable to remove marked videos

### ISSUE THREAD

**Issue by SuperPotatoGod** [sniklaus/youtube-watchmarker#34]
After the new update I'm no longer able to remove videos marked as watched, when I click the delete button it doesn't appear to do anything.

**Comment by sniklaus** [comment]
Thank you for bringing this up, I haven't implemented this feature in the rewrite yet.

https://github.com/sniklaus/youtube-watchmarker/blob/fae1c6ef5f9d3542a45de877cc9a71ea68982089/content/index.js#L512

This feature has actually not fully worked in the previous version since it did not delete the watched video from the browser history and from Youtube's history. As such, a deleted video was imported into the database again once the database synced with either the browser history or Youtube's history.

**Comment by SuperPotatoGod** [comment]
Was it not removing from youtube history a glitch or just not implemented? I had no idea it was meant to delete it there as well, I've just been manually removing videos from youtube history if I don't want them in watchmarker.

**Comment by sniklaus** [comment]
It wasn't implemented since I didn't realize that this was happening until recently. And since it is not straightforward to implement (removing it from Youtube's history is a little cumbersome), I have not included it when rewriting the extension. I am planning to reintroduce it, this time implemented correctly, in the next version.

**Comment by sniklaus** [comment]
I just uploaded a new version where removing a watched video from the database is fully supported. Thanks again for bringing this up, I am closing this issue for now but please reach out in case you encounter any problems.
