### ISSUE TITLE
Language Support "Watched" text [Feature Request]

### ISSUE THREAD

**Issue by k-y-a** [sniklaus/youtube-watchmarker#37]
Is it possible to modified the "Watched" text? Don't need full language support (settings). I just want to change the "Watched" text.

Thank you

**Comment by sniklaus** [comment]
I am afraid that I will not add this feature since I want to keep this extension as simple as possible to make it easier for me to maintain it, my apologies. However, I do not want to leave you without a solution, so here is what you could do. Download an extension that allows you to add CSS to a page, for example [Custom Style Script](https://addons.mozilla.org/en-US/firefox/addon/custom-style-script/) and then add the following CSS for Youtube.

```
.youwatch-mark:last-child:after {
	content:"WHATEVER YOU LIKE" !important;
}
```

If you are using the Custom Style Script then the rule for achieving this would be as follows.

![Screenshot_2020-04-26_20-15-01](https://user-images.githubusercontent.com/1238034/80330792-0645cc00-87fb-11ea-8292-38a9eb4727d2.png)
