### ISSUE TITLE
Unwatched videos being marked as watched anyway

### ISSUE THREAD

**Issue by Parent5446** [sniklaus/youtube-watchmarker#56]
## Overview

I can't quite tell what part is broken here, but I'm experiencing a fairly common situation where videos on the YouTube homepage are being marked as watched by the extension, despite not having ever watched them.

As an example, here is a video being shown as watched:
<img src="https://user-images.githubusercontent.com/52883/105941871-5ec92480-602c-11eb-8faf-64136f1195a1.png" height="300">

But when I search it in the extension's database, it doesn't show up:
<img src="https://user-images.githubusercontent.com/52883/105942326-047c9380-602d-11eb-9635-70f9a7ffcbc4.png" height="300">

And just as a sanity check, the video isn't in my Firefox browser history either (and I only watch YouTube in the browser):
<img src="https://user-images.githubusercontent.com/52883/105942397-2aa23380-602d-11eb-91da-a2bafaa9841e.png" height="300">

I thought perhaps the database search feature in the extension's page might be broken, but if I search for videos that I have definitely watched, they do show up. So I can only assume there's some problem with the matching method in which the extension is checking that a video exists in the database.

## My own debugging

I started looking at `youtube.js` and thought maybe it was being picked up by `objProgresscache`, but when I look in the console, the video in question (https://www.youtube.com/watch?v=GEfYa07fjd4) doesn't show up:
<img src="https://user-images.githubusercontent.com/52883/105943140-a18bfc00-602e-11eb-8ea5-b52e272004a7.png" height="300">

**Comment by Parent5446** [comment]
A quick followup: this _only_ happens on the YouTube homepage. If I go directly to the user's channel page, or if I find the video in my Subscriptions feed, it doesn't show up as watched.

**Comment by sniklaus** [comment]
Thank you for providing all this information! The issue isn't that the extension thinks that you watched the video, the issue is that YouTube will reuse HTML elements. In essence, there might have been a video that you actually watched and the extension marked it accordingly. Then, the element becomes no longer necessary (for example because you navigated to a different page) and instead of deleting it, YouTube places into a cache. Then, when a new video is ought to be shown in the list, YouTube first reuses previously used elements from its cache (for the sake of efficiency, probably). However, the HTML element in the cache has already been marked as watched but it is now being used for a different video. This is, unfortunately, quite difficult to detect so my current implementation may not work reliably on YouTube's homepage. I will have to look into this further in the future. :+1:

**Comment by Almashina** [comment]
Hi there!
The same issue when use in YT button "back" for return to YT main page, for example.

**Comment by drejjmit** [comment]
This is still a problem on main page. 
Can't you just check the video-title-link?

**Comment by MinuteAd8502** [comment]
I notice that problem only in sidebar to the right when already watching some video. But not in search results. Using option like "hide related videos" in Enhancer for Youtube extension is good temporary solution, but not really a solution.

**Comment by jmg999** [comment]
I've also experienced this problem in a couple of different ways.  First, videos that show up as recommendations in the right-hand column are beginning to be marked as watched, and second, I'd noticed that if I pulled up a playlist and played a single video, all the videos in the playlist would be marked as watched.  This became really confusing to try to organize, b/c some playlists have dozens of videos.

**Comment by JustAnOkapi** [comment]
I get videos I have never seen that came out hours ago marked as watched. They are normally at the top of the sidebar recommendations. 

![image](https://user-images.githubusercontent.com/39418801/151920238-2bd7549a-4d03-4192-a9a3-269f1ba18ad7.png)

**Comment by JustAnOkapi** [comment]
A few minutes later when I exited full screen the video was no longer marked.

![image](https://user-images.githubusercontent.com/39418801/151920743-b979ce31-1816-4002-9fd4-d484b8f9ebb9.png)

**Comment by sniklaus** [comment]
Please see: https://github.com/sniklaus/youtube-watchmarker/issues/56#issuecomment-770324096

**Comment by JustAnOkapi** [comment]
This is not on the homepage. Its on the recommendation sidebar.

**Comment by sniklaus** [comment]
The explanation in the linked comment also applies to the sidebar.

**Comment by qstar-inc** [comment]
I've seeing this issue on the subscription page as well; I understand how it happens on sidebar/homepage; but why subscription? Also, when the position of that particular video moved (when other subscribed channels added a new video), it no longer have the Watched fade.

**Comment by lbmaian** [comment]
@sniklaus FWIW I'm not sure if my changes would've fixed this. I personally never use the YT homepage so I don't recall encountering this issue.

Perhaps one way to ensure this is fixed is to monitor for `yt-navigate-finish` events (`window` or `document.addEventListener('yt-navigate-finish', ...)` and clear `boolMarkcache` there.

**Comment by JustAnOkapi** [comment]
the issue seemed to be caused by yt caching thumbnails

**Comment by lbmaian** [comment]
Oh I didn't see later comments that this happens for video recommendations and subscriptions. I've only seen videos NOT being marked as watched despite being recorded as such in watchmarker. That should've been due to thumbnail image caching (by the browser, not YT), which should've been fixed.

What's likely happening here is outlined in https://github.com/sniklaus/youtube-watchmarker/issues/56#issuecomment-770324096 - HTML elements being reused when "internally" navigating between YT pages. Hence my suggestion of clearing the cache whenever the page changes via a yt-navigate-finish event listener.

**Comment by sniklaus** [comment]
> Perhaps one way to ensure this is fixed is to monitor for yt-navigate-finish events (window or document.addEventListener('yt-navigate-finish', ...)) and clear boolMarkcache there.

Thank you for the suggestion, that is a nifty idea! I am currently using the following mechanism to detect changes which is definitely less efficient but maybe more general. I'll also add the `yt-navigate-finish` listener. :+1: 

https://github.com/sniklaus/youtube-watchmarker/blob/0cb11b1f30c17243505710aa14741a3ac9c5c2b8/youtube.js#L89-L104

**Comment by lbmaian** [comment]
Well yt-navigate-finish doesn't catch everything, since more videos are loaded as you scroll down, so you still do need the existing interval check. There's might be other custom events that can catch when the new videos are actually inserted into the page, or a MutationObserver to monitor for them, but AFAIK the custom yt-navigate-finish event should catch all the cases where videos are wiped or replaced on the page.

**Comment by lbmaian** [comment]
Actually I take that back, changing sort order probably also reuses HTML elements. I believe the yt-service-request-completed custom event can catch such cases, firing after the HTML elements are added (I think? needs to be checked), though the event doesn't always fire when scrolling down to load more videos (YT page internally may include more video data than it actually creates video HTML elements for, only inserting them when scrolling down).

So maybe a combination of existing check and new yt-navigate-finish + yt-service-request-completed listeners would suffice?

**Comment by utkarshgupta137** [comment]
I have started seeing this on my subscriptions page too recently. I also use a few other YouTube extensions, most prominently PocketTube to hide the watched videos completely. The thing is that the watched marker comes on after a few minutes (I have a pinned tab with the sub-page always open). I'll check if there is any pattern or anything.

**Comment by sniklaus** [comment]
I will incorporate @lbmaian's excellent suggestions and work on a new version tonight. It will invalidate the cache when receiving either the `'yt-service-request-completed'` or the `'yt-navigate-finish'` event. Please let me know whether the new version, which may take a few days to land, helps with this issue once and for all. Thanks!

**Comment by Terrance** [comment]
Just got the 4.4.1 update and that seems to handle switching between channel video tabs nicely.  🙂

**Comment by sniklaus** [comment]
Thanks for letting me know! I will close this issue for now but am sure we'll have to revisit this in the future again. So please don't hesitate to comment if the issue persists and I'll reopen it. :+1:

**Comment by githubjsorg** [comment]
> Thanks for letting me know! I will close this issue for now but am sure we'll have to revisit this in the future again. So please don't hesitate to comment if the issue persists and I'll reopen it. 👍

This is still an issue. And it looks like someone has opened a new ticket for it.
[https://github.com/sniklaus/youtube-watchmarker/issues/196](url)
