### ISSUE TITLE
PotPlayer+Watchmarker

### ISSUE THREAD

**Issue by Alexey71** [sniklaus/youtube-watchmarker#63]
When I click on the video, link opens to PotPlayer, Watchmarker does not work. Can you make a marker while clicking on the link  and marker when the link is copied? 
And make the ability to tranlation"Warched" on other language

**Comment by sniklaus** [comment]
Searching for "PotPlayer" on Firefox's addon page only shows one relevant extension with 1.4k users. The overlap between users of the Youtube Watchmaker, which itself only has 1.7k users, and users of the PotPlayer extension is expected to be small. I am thus sorry to say that this request is too niche for me to support, my apologies.

![image](https://user-images.githubusercontent.com/1238034/120533243-5fd0e080-c395-11eb-99bf-784832af1874.png)

**Comment by Alexey71** [comment]
Extension of the chrome 20,000+, other VLC players, MPV, MPC-BE... Did you count it?
Most do not look at the site, they send a link to their favorite player

**Comment by sniklaus** [comment]
Even with 20k users on Chrome, there is probably less than 10 users who use both the PotPlayer as well as the Youtube Watchmarker. Besides, as long as the video shows up in https://www.youtube.com/feed/history the Youtube Watchmarker will keep track of it.

**Comment by Alexey71** [comment]
I asked that when **copying or clicking on the link, it was marked as viewed**. Potplayer was specified as for example. And do not pay attention to him) 
If you help with the code, i can))

**Comment by sniklaus** [comment]
So you request a feature that only you need, effectively asking me to spend my limited time to serve your needs. I politely decline your request since it is too niche and my spare time is limited, suggesting that you add the feature yourself. And then you go ahead and rate this extension with 1 star (the only 1 star rating of this addon). Do you think your behavior is appropriate?

![image](https://user-images.githubusercontent.com/1238034/120883662-4b5a3700-c593-11eb-8c49-c2dc0465cfea.png)
Source: https://addons.mozilla.org/en-US/firefox/addon/watchmarker-for-youtube/reviews/1717898/

Some facts: 1) this is a free extension and nobody forces you to use it, 2) this extension is open source and you can just modify it to fit your needs, 3) demanding that I add a feature just because you need it is egoistic, 4) I will not be bullied by you, and 5) you make yourself look like a douchebag.

**Comment by Alexey71** [comment]
Realy? Now all "Alexey" is me for your? I already forgot about your extension, and did not insult you 
![firefox_3840x2040_05-06-2021_10H-40M-34S](https://user-images.githubusercontent.com/10572914/120884355-72dcee00-c5eb-11eb-9d97-98c60c59f040.jpg)

**Comment by sniklaus** [comment]
Your response initially included a screenshot to "prove" that it is not you who wrote the review. You edited your response by now though and removed the screenshot, so I looked a little closer at it. I don't know why, but there is a smaller section on the bottom right that I magnified below.

![image](https://user-images.githubusercontent.com/1238034/120897857-0e1a9700-c5dd-11eb-88a5-31d22dab62e5.png)

So yes, the review very much was from you. Thanks for confirming that.
