### ISSUE TITLE
possible compatibility problem with Iridium on Firefox 58.0.2 x64

### ISSUE THREAD

**Issue by gnivler** [sniklaus/youtube-watchmarker#7]
The Iridium plugin adds 'quick controls' that allow for blocking whole channels.  Those buttons are overlaid on each video thumbnail but they don't appear when I have Watchmarker enabled as well.

I have a few other addons but disabled them all except these two.

To replicate it should be as easy as enabling Watchmarker with Iridium also enabled in Firefox.  Hover a video thumbnail to see the difference.  Pic of the overlay buttons included.

Hope this is helpful, I like the add-on!

![2018-03-07_125918](https://user-images.githubusercontent.com/18452645/37112272-8b052c80-2207-11e8-9165-e9f3a9e06017.png)

**Comment by sniklaus** [comment]
Can confirm, thank you for bringing this to my attention. This might be difficult to get work properly, since both extensions are interacting with the webpage and modify it in certain ways. For example, the Youtube Watchmarker adds an id attribute to every video in order to reference it. Iridium might do this as well, but only one id can be assigned at a time. Youtube Watchmaker might in this regard execute later and hence overwrite the changes from Iridium. I will take a look at this in more detail if I have the time.

- Simon

**Comment by sniklaus** [comment]
I am happy to announce that I released a new version where this should no longer be a problem. I am hence closing this issue for now. Thanks again for bringing this to my attention and please let me know in case the problem prevails.
