### ISSUE TITLE
fading thumbnails out and converting them to grayscale no longer works

### ISSUE THREAD

**Issue by nijazm** [sniklaus/youtube-watchmarker#90]
They have done lots of changes of YouTube, everything is different. Today noticed grayscale and fading out of watched videos by your extension no longer works. Now only works that textual badge.

**Comment by jeefmaze** [comment]
Can confirm this issue as well. 
Tested on
Librewolf 106.0.4 
YouTube Watchmarker Version 4.2.1

**Comment by sniklaus** [comment]
I would be happy to debug this but I am not having this issue (yet), see the screenshot below.
![image](https://user-images.githubusercontent.com/1238034/200710467-401a6418-14e7-4a94-86ff-da2403a5645f.png)
Could someone post a screenshot of how it looks for them? Like, did the Youtube interface change?

**Comment by jeefmaze** [comment]
![image](https://user-images.githubusercontent.com/53583661/200712087-9b82bce0-ae18-4e8f-a04f-248d08d199cd.png)

**Comment by Lairdom** [comment]
I think youtube pushes updates at different times for different regions or something. I've seen videos where people are talking about recent changes to youtube and being confused because nothing was different for me. And then like a month later I suddenly get changes and being confused since no one is talking about them.

This issue also started quite suddenly. Everything was working fine earlier today. I have seen the changes in their interface for a few days(weeks?) now. Like the way the playlists look now.

**Comment by 0xva** [comment]
I sent a pull request fixing this issue.
I'm new to github so I hope i did right.

**Comment by sniklaus** [comment]
Thanks everyone for chiming in! I just uploaded a new version which is already out for Firefox but still under review for Chrome (no idea how long this takes). Please let me know whether or not the version 4.2.2 fixes this issue, thanks!

**Comment by jeefmaze** [comment]
Can confirm 4.2.2 works. Thanks!

**Comment by sniklaus** [comment]
The listing for Chrome now shows 4.2.2 as well, let me know how it goes. :+1:

**Comment by Lairdom** [comment]
Works great! You do gods work, man. Thank you.

**Comment by nijazm** [comment]
Yup, works here!

**Comment by sniklaus** [comment]
Thanks y'all for confirming! I am hence closing this issue for now, please let me know (by replying here or by opening up a new issue) if this issue comes back or wasn't resolved after all. Thanks!
